version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taskmanagerdb     # Database name
      POSTGRES_USER: admin           # Database username
      POSTGRES_PASSWORD: pass        # Database password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Spring Boot Backend Service
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/taskmanagerdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - localhost
    ports:
      - "8080:8080"
    networks:
      - app-network

  # React Frontend Service
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

# Define Docker volumes for persistent storage
volumes:
  postgres_data:

# Define the network
networks:
  app-network:
